
<html>
    <h1>Employee Details</h1><br><br>
<div class=row>
    <div class=col><b><h3>Employee Id</h3></b></div>
    <div class=col><b><h3>Employee Name</h3></b></div>
    <div class=col><b><h3>Company Name</h3></b></div>
    <div class=col></div>
    <div class=col></div>
</div>
    <br><br>
<?php foreach($emp as $emp): ?>
<div class=row>
    
    <div class=col> 
    <h3><?= $this->escapeHtml($emp->getId()); ?>  </h3>
    </div>
        
 
    <div class=col>
   <h3><?= $this->escapeHtml($emp->getEmpName()); ?></h3>
</div>


    <div class=col>
   <h3><?= $this->escapeHtml($emp->getCmpName()); ?></h3>
 </div> 
 
    <div class=col>
        <a href="/crud/edit/<?= $this->escapeHtml($emp->getId()); ?> "><h3>Edit</h3></a>
 </div>   
 
    <div class=col>
        <a href="/crud/delete/<?= $this->escapeHtml($emp->getId()); ?> "><h3>Delete</h3></a>
</div>
</div>

<?php endforeach; ?>
    <a href="/crud/add"><h3>Insert New Row</h3></a>
</html>